spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    password: password
    url: 'jdbc:mysql://192.168.1.105:3306/roomescape?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul'
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
